<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contract - {{ $clinic->name }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 20px;
            line-height: 1.5;
        }

        .header {
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .title {
            font-size: 18px;
            font-weight: bold;
            color: #007bff;
        }

        .subtitle {
            font-size: 13px;
            color: #555;
            margin-top: 4px;
        }

        .meta {
            margin-top: 8px;
            font-size: 11px;
        }

        .meta div {
            margin-bottom: 2px;
        }

        .section-title {
            font-size: 14px;
            font-weight: bold;
            margin: 20px 0 8px;
            color: #007bff;
        }

        .contract-body {
            font-size: 11px;
            text-align: justify;
        }

        .summary-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
            margin-top: 10px;
        }

        .summary-table td {
            padding: 4px 6px;
            border: 1px solid #ddd;
        }

        .summary-table td.label {
            width: 30%;
            font-weight: bold;
            background: #f8f9fa;
        }

        .footer {
            margin-top: 40px;
            font-size: 10px;
            color: #777;
            text-align: center;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $contract->contract_title ?? 'Service Agreement' }}</div>
        <div class="subtitle">Clinic: {{ $clinic->name }}</div>
        <div class="meta">
            <div><strong>Contract ID:</strong> #{{ $contract->id }}</div>
            @if($contract->start_date)
                <div><strong>Start Date:</strong> {{ $contract->start_date->format('Y-m-d') }}</div>
            @endif
            @if($contract->end_date)
                <div><strong>End Date:</strong> {{ $contract->end_date->format('Y-m-d') }}</div>
            @endif
            <div><strong>Status:</strong> {{ ucfirst($contract->status) }}</div>
            @isset($generatedAt)
                <div><strong>Generated At:</strong> {{ $generatedAt->format('Y-m-d H:i') }}</div>
            @endisset
        </div>
    </div>

    <table class="summary-table">
        <tr>
            <td class="label">Clinic Name</td>
            <td>{{ $clinic->name }}</td>
        </tr>
        @if($clinic->address)
        <tr>
            <td class="label">Clinic Address</td>
            <td>{{ $clinic->address }}</td>
        </tr>
        @endif
        @if($clinic->phone)
        <tr>
            <td class="label">Clinic Phone</td>
            <td>{{ $clinic->phone }}</td>
        </tr>
        @endif
        @if($clinic->email)
        <tr>
            <td class="label">Clinic Email</td>
            <td>{{ $clinic->email }}</td>
        </tr>
        @endif
        @if($contract->annual_fee)
        <tr>
            <td class="label">Annual Fee</td>
            <td>{{ number_format($contract->annual_fee, 0) }} IQD</td>
        </tr>
        @endif
        @if($contract->contract_duration_months)
        <tr>
            <td class="label">Duration</td>
            <td>{{ $contract->contract_duration_months }} months</td>
        </tr>
        @endif
    </table>

    <div class="section-title">Terms and Conditions</div>

    <div class="contract-body">
        {!! nl2br(e($contractContent)) !!}
    </div>

    @if($contract->status === 'accepted' && $contract->accepted_at)
        <div class="section-title">Acceptance</div>
        <div class="contract-body">
            <p>
                This contract was accepted on {{ $contract->accepted_at->format('Y-m-d H:i') }}
                @if($contract->acceptedBy)
                    by {{ $contract->acceptedBy->full_name ?? $contract->acceptedBy->username }}.
                @else
                    by the clinic administrator.
                @endif
            </p>
        </div>
    @endif

    <div class="footer">
        ConCure Cloud - Master contract copy. Generated by the Master admin panel.
    </div>
</body>
</html>
